version: "3.9"

services:

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    ports:
        - "8080:80"
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
      
  backend:
    image: ${DOCKER_REGISTRY-}backend
    ports:
      - "4000:80"
    build:
      context: .
      dockerfile: ./Backend/Dockerfile