version: "3.9"

services:

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: ./Backend/Dockerfile

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    ports:
      - "8000:5000"
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile