version: '3.4'

services:
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    ports:
      - "8000:5000"
    build:
      context: .
      dockerfile: ../Frontend/Dockerfile

  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: Backend/Dockerfile